### ISSUE TITLE
OLS connectivity issues

### ISSUE THREAD

**Issue by OwenLeiser** [PRIDE-Toolsuite/ols-dialog#6]
I am trying to upload a dataset using the tool (v2.4.7), and it will not connect to OLS for choosing a species not on the preset list. Is this a known problem, and is there a timeline for resolving it? Thanks!

**Comment by ypriverol** [comment]
Hi @OwenLeiser We will have a quick look today and go back to you.

**Comment by sureshhewabi** [comment]
Hi @OwenLeiser,

Sorry for the late replay. However OLS Dialog in the Px Submission tool(v2.4.7) works fine and we cannot replicate any issues.

<img width="1196" alt="screen shot 2018-06-20 at 13 50 05" src="https://user-images.githubusercontent.com/5387193/41659423-30c258f6-7491-11e8-9861-a70669ada392.png">

When you choose "Others" from species dropdown, there can be a delay to load OLS Dialog since it fetches data online. If you still experience the issue, could you please add more information to replicate it.Thanks!
